configName: pic32mz_ef_sk
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: PIC32MZ2048EFH144
projectName: ''
settings:
  PackageFilter: audio;bsp;core;csp;quick_docs;usb;usb_apps_device;usb_apps_dual_role;usb_apps_host;usb_apps_multi_controller
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-EF_DFP\1.3.58\atdf\PIC32MZ2048EFH144.atdf
